export const ALL_PRODUCT_REQUEST = 'ALL_PRODUCT_REQUEST';
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS';
export const ALL_PRODUCT_FAIL = 'ALL_PRODUCT_FAIL';

export const ALL_TRENDING_PRODUCT_REQUEST = 'ALL_TRENDING_PRODUCT_REQUEST';
export const ALL_TRENDING_PRODUCT_SUCCESS = 'ALL_TRENDING_PRODUCT_SUCCESS';
export const ALL_TRENDING_PRODUCT_FAIL = 'ALL_TRENDING_PRODUCT_FAIL';

export const TRENDING_PRODUCT_REQUEST = 'TRENDING_PRODUCT_REQUEST';
export const TRENDING_PRODUCT_SUCCESS = 'TRENDING_PRODUCT_SUCCESS';
export const TRENDING_PRODUCT_FAIL = 'TRENDING_PRODUCT_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
